DROP TABLE IF EXISTS User;

CREATE TABLE `User` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT ,
    `Email` VARCHAR(150) NOT NULL ,
    `Password` VARCHAR(255) NOT NULL ,
    `FirstName` VARCHAR(75) NOT NULL ,
    `LastName` VARCHAR(75) NOT NULL ,
    `IsAdmin` BOOLEAN NOT NULL ,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;
